if(WIN32)
    if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd26812 /w34456 /w34457 /w34458 /w34459 /w35038 /we4715 /we4834 /we4172 /wd4244")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /ignore:4099 /ignore:4075")
    else() # Assume MinGW
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror=return-type -Werror=unused-result -Werror=return-local-addr -ftrivial-auto-var-init=pattern")
    endif()
elseif(LINUX)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror=return-type -Werror=unused-result -Werror=return-local-addr -ftrivial-auto-var-init=pattern")
elseif(APPLE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror=return-type -Werror=unused-result -Werror=return-stack-address -ftrivial-auto-var-init=pattern")
elseif(EMSCRIPTEN)
    set(CMAKE_EXECUTABLE_SUFFIX ".html")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -sMIN_WEBGL_VERSION=2 -sTOTAL_MEMORY=1024MB --shell-file \"${PROJECT_SOURCE_DIR}/../External/Emscripten/shell_minimal.html\"")
    if (EXISTS "Assets" AND IS_DIRECTORY "Assets")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --preload-file \"${PROJECT_SOURCE_DIR}/Assets@/Assets\"")
    endif()
    if (EXISTS "ShadersES" AND IS_DIRECTORY "ShadersES")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --preload-file \"${PROJECT_SOURCE_DIR}/${GAMENAME}/ShadersES@/Shaders\"")
    endif()
endif()
